name: 'Get and Cache dependencies'
description: 'Get and cache node modules'
inputs:
  caching:
    description: Do you want to cache?
    default: 'true'
    required: false
outputs:
  result:
    description: Used cached dependencies?
    value: ${{ steps.installed-deps.outputs.cached }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: 'cache-deps'
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install deps
      if: steps.cache-deps.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: yarn
      shell: bash
    - name: check cashed
      id: installed-deps
      run: echo "cached='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash