name: 'Get and Cache dependencies'
description: 'Get and cache node modules'
inputs:
  caching:
    description: Do you want to cache?
    default: 'true'
    required: false
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: 'cache-deps'
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install deps
      if: steps.cache-deps.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: yarn
      shell: bash