name: Deploy project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: install deps
        run: yarn
      - name: run test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: create build
        run: yarn run build
      - name: deploy
        run: echo deploying...
