name: Reusable action
on: 
  workflow_call:
    inputs:
      dummy-text:
        description: 'Dummy text'
        type: string
        required: false
        default: 'dummy value'
    secrets:
      dummy-secret:
        required: true
      
jobs:
  print-github-content:
    runs-on: ubuntu-latest
    steps:
      - name: Print github content
        run: |
          echo Printing github content...
          echo ${{ inputs.dummy-text }}
          echo ${{ secrets.dummy-secret }}
