name: Reusable action
on: workflow_call
inputs:
  dummy_text:
    description: 'Dummy text'
    required: false
    default: 'dummy value'
jobs:
  print-github-content:
    runs-on: ubuntu-latest
    steps:
      - name: Print github content
        run: |
          echo Printing github content...
          echo ${{ inputs.dummy_text }}
