name: Reusable action
on: 
  workflow_call:
    inputs:
      dummy-text:
        description: 'Dummy text'
        type: string
        required: false
        default: 'dummy value'
    secrets:
      dummy-secret:
        required: true
    outputs:
      result: 
        description: 'Result of the reusable action'
        value: ${{ jobs.print-github-content.outputs.outcome }}
      
jobs:
  print-github-content:
    outputs:
      outcome: ${{ steps.job-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Print github content
        run: |
          echo Printing github content...
          echo ${{ inputs.dummy-text }}
          echo ${{ secrets.dummy-secret }}
      - name: output
        id: job-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
